version: "3.8"

services:
  django-app:
    build:
      context: .
    volumes:
      - .:/corruption
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=corruption.settings
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=your_db_name
      - DATABASE_USER=your_user
      - DATABASE_PASSWORD=your_password

  mysql-db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: your_db_name
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password

volumes:
  mysql_data:
