name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: corruption_db
          POSTGRES_USER: corruption_db_user
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U corruption_db_user -d corruption_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env
          echo "DEBUG=True" >> .env
          echo "ALLOWED_HOSTS=127.0.0.1,localhost" >> .env
          echo "DB_NAME=corruption_db" >> .env
          echo "DB_USER=corruption_db_user" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Run migrations and tests
        run: |
          python manage.py migrate
          python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/django-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest
