name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      # PostgreSQL service for testing
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: corruption_db
          POSTGRES_USER: corruption_db_user
          POSTGRES_PASSWORD: Cr6PzluGY8XQhQGygYz031rKqYRCoCvD
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U corruption_db_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Wait for PostgreSQL to be ready
      - name: Wait for PostgreSQL to be ready
        run: |
          chmod +x ./wait-for-it.sh
          ./wait-for-it.sh postgres:5432 --timeout=60 --strict -- echo "Postgres is up"

      # Run migrations and tests
      - name: Run migrations and tests
        env:
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
          DATABASE_NAME: corruption_db
          DATABASE_USER: corruption_db_user
          DATABASE_PASSWORD: Cr6PzluGY8XQhQGygYz031rKqYRCoCvD
        run: |
          python manage.py migrate
          python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/django-app:latest
